name: CI
on: [push]

jobs:
  test-ui:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 14.17.3
        uses: actions/setup-node@v1
        with:
          node-version: 14.17.3
      - name: "Navigate to UI folder"
        run: cd ui
      - name: "Run Tests"
        run: npm test